export const GET_ISSUE = 'GET_ISSUE';
export const GET_ISSUE_SUCCESS = 'GET_ISSUE_SUCCESS';
export const GET_ISSUE_ERROR = 'GET_ISSUE_ERROR';

export const GET_ISSUES = 'GET_ISSUES';
export const GET_ISSUES_SUCCESS = 'GET_ISSUES_SUCCESS';
export const GET_ISSUES_ERROR = 'GET_ISSUES_ERROR';

export const GET_ISSUES_STATUSES = 'GET_ISSUES_STATUSES';
export const GET_ISSUES_STATUSES_SUCCESS = 'GET_ISSUES_STATUSES_SUCCESS';
export const GET_ISSUES_STATUSES_ERROR = 'GET_ISSUES_STATUSES_ERROR';
